spring:
  application:
         name: Device-registration
  datasource:
    url: jdbc:mysql://localhost:2208/vehicle_data
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/master/protocol/openid-connect/certs
keycloak:
  realm: master
  auth-server-url: http://localhost:8181/auth
  resource: admin-cli
  credentials:
    secret: kOmejrrDAR7zOnmX8xeMmq1MASFc8dM9




